project:
  type: book

book:
  title: "fect -- User Manual"
  sidebar:
    style: docked
    background: light
  chapters:
    - index.qmd
    - 01-start.Rmd
    - 02-fect.Rmd
    - 03-ife-mc.Rmd
    - 04-cfe.Rmd
    - 05-diagnostics.Rmd
    - 06-model-selection.Rmd
    - 07-plots.Rmd
    - 08-gsynth.Rmd
    - 09-panel.Rmd
    - 10-sens.Rmd
    - aa-cheatsheet.Rmd
    - references.qmd

bibliography: references.bib

nocite: |
  @*

suppress-bibliography: true

format:
  html:
    theme: cosmo
    code-fold: false
    code-tools: true
    code-link: true
    toc: true
    toc-depth: 3
    toc-expand: 2

knitr:
  opts_chunk:
    collapse: true
    comment: "#>"

editor: visual
