name: release-to-cran-and-docs

on:
  workflow_dispatch:
    inputs:
      submit_to_cran:
        description: "Submit to CRAN (requires secrets.GH_PAT and CRAN_EMAIL set)"
        required: true
        default: "false"
      tag:
        description: "Git tag to create (e.g., v2.0.3)"
        required: true

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag ${{ github.event.inputs.tag }}
          git push origin ${{ github.event.inputs.tag }}

  submit-cran:
    if: ${{ github.event.inputs.submit_to_cran == 'true' }}
    needs: tag-release
    runs-on: ubuntu-latest
    env:
      R_KEEP_PKG_SOURCE: yes
      _R_CHECK_CRAN_INCOMING_REMOTE_: false
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      CRAN_EMAIL: ${{ secrets.CRAN_EMAIL }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::devtools
            any::rcmdcheck
            any::pkgdown
            local::.
          needs: check
      - name: Install GitHub packages (HonestDiDFEct)
        run: |
          R -q -e "if (!requireNamespace('devtools', quietly=TRUE)) install.packages('devtools', repos='https://cloud.r-project.org')"
          R -q -e "if (!requireNamespace('HonestDiDFEct', quietly=TRUE)) devtools::install_github('lzy318/HonestDiDFEct')"
      - name: CRAN checks (as-cran)
        run: |
          R -q -e "rcmdcheck::rcmdcheck(args=c('--no-manual','--as-cran'), error_on='warning')"
      - name: Submit to CRAN (manual email)
        run: |
          R -q -e "devtools::build('.')"
          echo "Please email the built tar.gz to CRAN maintainers from $CRAN_EMAIL or use devtools::release() interactively."

  pkgdown:
    needs: tag-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
      - name: Install GitHub packages (HonestDiDFEct)
        run: |
          R -q -e "if (!requireNamespace('devtools', quietly=TRUE)) install.packages('devtools', repos='https://cloud.r-project.org')"
          R -q -e "if (!requireNamespace('HonestDiDFEct', quietly=TRUE)) devtools::install_github('lzy318/HonestDiDFEct')"
      - name: Build site
        run: |
          R -q -e "pkgdown::build_site(preview = FALSE)"
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs


