name: test-and-check

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      R_KEEP_PKG_SOURCE: yes
      _R_CHECK_CRAN_INCOMING_REMOTE_: false
      _R_CHECK_FORCE_SUGGESTS_: false
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::devtools
            any::testthat
            local::.
          needs: tests
      - name: Install GitHub packages (HonestDiDFEct)
        run: |
          R -q -e "if (!requireNamespace('devtools', quietly=TRUE)) install.packages('devtools', repos='https://cloud.r-project.org')"
          R -q -e "if (!requireNamespace('HonestDiDFEct', quietly=TRUE)) devtools::install_github('lzy318/HonestDiDFEct')"
      - name: Run tests
        run: |
          R -q -e "devtools::test()"

  cran-check:
    needs: test
    runs-on: ubuntu-latest
    env:
      R_KEEP_PKG_SOURCE: yes
      _R_CHECK_CRAN_INCOMING_REMOTE_: false
      _R_CHECK_FORCE_SUGGESTS_: false
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            local::.
          needs: check
      - name: Install GitHub packages (HonestDiDFEct)
        run: |
          R -q -e "if (!requireNamespace('devtools', quietly=TRUE)) install.packages('devtools', repos='https://cloud.r-project.org')"
          R -q -e "if (!requireNamespace('HonestDiDFEct', quietly=TRUE)) devtools::install_github('lzy318/HonestDiDFEct')"
      - name: CRAN incoming checks
        run: |
          R -q -e "rcmdcheck::rcmdcheck(args = c('--no-manual','--as-cran'), error_on='warning', check_dir='check')"
      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cran-check-results
          path: check


