name: test-and-check

on:
  push:
    branches: [ main, master, fectbook ]
  pull_request:
    branches: [ main, master, fectbook ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      R_KEEP_PKG_SOURCE: yes
      _R_CHECK_CRAN_INCOMING_REMOTE_: false
      _R_CHECK_FORCE_SUGGESTS_: false
      RGL_USE_NULL: true
    steps:
      - uses: actions/checkout@v4
      - name: Clean precompiled objects
        shell: bash
        run: |
          rm -f src/*.o src/*.so src/*.dll || true
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::devtools
            any::testthat
            lzy318/HonestDiDFEct
            local::.
          needs: tests
          cache-version: 2
      - name: Install HonestDiDFEct via devtools
        shell: Rscript {0}
        run: |
          if (!requireNamespace('remotes', quietly=TRUE)) install.packages('remotes', repos='https://cloud.r-project.org')
          if (!requireNamespace('HonestDiDFEct', quietly=TRUE)) remotes::install_github('lzy318/HonestDiDFEct', upgrade='never')
      - name: Run tests
        shell: Rscript {0}
        run: |
          devtools::test()

  cran-check:
    needs: test
    runs-on: ubuntu-latest
    env:
      R_KEEP_PKG_SOURCE: yes
      _R_CHECK_CRAN_INCOMING_REMOTE_: false
      _R_CHECK_FORCE_SUGGESTS_: false
      RGL_USE_NULL: true
    steps:
      - uses: actions/checkout@v4
      - name: Clean precompiled objects
        shell: bash
        run: |
          rm -f src/*.o src/*.so src/*.dll || true
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            lzy318/HonestDiDFEct
            local::.
          needs: check
          cache-version: 2
      - name: Install HonestDiDFEct via devtools
        shell: Rscript {0}
        run: |
          if (!requireNamespace('remotes', quietly=TRUE)) install.packages('remotes', repos='https://cloud.r-project.org')
          if (!requireNamespace('HonestDiDFEct', quietly=TRUE)) remotes::install_github('lzy318/HonestDiDFEct', upgrade='never')
      - name: CRAN incoming checks
        shell: Rscript {0}
        run: |
          rcmdcheck::rcmdcheck(args = c('--no-manual','--as-cran'), error_on='warning', check_dir='check')
      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cran-check-results
          path: check


